// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contact.proto

package pb

import (
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CheckInRequest struct {
	Address  string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Version  *NodeVersion  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capacity *NodeCapacity `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Operator *NodeOperator `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	// CheckIn may happen over TLS, which means there is not necessarily an
	// opportunity to use NoiseSessionAttestation instead of
	// NoiseKeyAttestation.
	NoiseKeyAttestation *NoiseKeyAttestation `protobuf:"bytes,5,opt,name=noise_key_attestation,json=noiseKeyAttestation,proto3" json:"noise_key_attestation,omitempty"`
	DebounceLimit       int32                `protobuf:"varint,6,opt,name=debounce_limit,json=debounceLimit,proto3" json:"debounce_limit,omitempty"`
	// features is a set of bit flags of the NodeAddress.Features enum.
	Features             uint64             `protobuf:"varint,7,opt,name=features,proto3" json:"features,omitempty"`
	SignedTags           *SignedNodeTagSets `protobuf:"bytes,8,opt,name=signed_tags,json=signedTags,proto3" json:"signed_tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CheckInRequest) Reset()         { *m = CheckInRequest{} }
func (m *CheckInRequest) String() string { return proto.CompactTextString(m) }
func (*CheckInRequest) ProtoMessage()    {}
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}
func (m *CheckInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInRequest.Unmarshal(m, b)
}
func (m *CheckInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInRequest.Marshal(b, m, deterministic)
}
func (m *CheckInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInRequest.Merge(m, src)
}
func (m *CheckInRequest) XXX_Size() int {
	return xxx_messageInfo_CheckInRequest.Size(m)
}
func (m *CheckInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInRequest proto.InternalMessageInfo

func (m *CheckInRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CheckInRequest) GetVersion() *NodeVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *CheckInRequest) GetCapacity() *NodeCapacity {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *CheckInRequest) GetOperator() *NodeOperator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *CheckInRequest) GetNoiseKeyAttestation() *NoiseKeyAttestation {
	if m != nil {
		return m.NoiseKeyAttestation
	}
	return nil
}

func (m *CheckInRequest) GetDebounceLimit() int32 {
	if m != nil {
		return m.DebounceLimit
	}
	return 0
}

func (m *CheckInRequest) GetFeatures() uint64 {
	if m != nil {
		return m.Features
	}
	return 0
}

func (m *CheckInRequest) GetSignedTags() *SignedNodeTagSets {
	if m != nil {
		return m.SignedTags
	}
	return nil
}

type CheckInResponse struct {
	PingNodeSuccess      bool     `protobuf:"varint,1,opt,name=ping_node_success,json=pingNodeSuccess,proto3" json:"ping_node_success,omitempty"`
	PingErrorMessage     string   `protobuf:"bytes,2,opt,name=ping_error_message,json=pingErrorMessage,proto3" json:"ping_error_message,omitempty"`
	PingNodeSuccessQuic  bool     `protobuf:"varint,3,opt,name=ping_node_success_quic,json=pingNodeSuccessQuic,proto3" json:"ping_node_success_quic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInResponse) Reset()         { *m = CheckInResponse{} }
func (m *CheckInResponse) String() string { return proto.CompactTextString(m) }
func (*CheckInResponse) ProtoMessage()    {}
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}
func (m *CheckInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInResponse.Unmarshal(m, b)
}
func (m *CheckInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInResponse.Marshal(b, m, deterministic)
}
func (m *CheckInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInResponse.Merge(m, src)
}
func (m *CheckInResponse) XXX_Size() int {
	return xxx_messageInfo_CheckInResponse.Size(m)
}
func (m *CheckInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInResponse proto.InternalMessageInfo

func (m *CheckInResponse) GetPingNodeSuccess() bool {
	if m != nil {
		return m.PingNodeSuccess
	}
	return false
}

func (m *CheckInResponse) GetPingErrorMessage() string {
	if m != nil {
		return m.PingErrorMessage
	}
	return ""
}

func (m *CheckInResponse) GetPingNodeSuccessQuic() bool {
	if m != nil {
		return m.PingNodeSuccessQuic
	}
	return false
}

type GetTimeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimeRequest) Reset()         { *m = GetTimeRequest{} }
func (m *GetTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTimeRequest) ProtoMessage()    {}
func (*GetTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{2}
}
func (m *GetTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeRequest.Unmarshal(m, b)
}
func (m *GetTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeRequest.Marshal(b, m, deterministic)
}
func (m *GetTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeRequest.Merge(m, src)
}
func (m *GetTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTimeRequest.Size(m)
}
func (m *GetTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeRequest proto.InternalMessageInfo

type GetTimeResponse struct {
	Timestamp            time.Time `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTimeResponse) Reset()         { *m = GetTimeResponse{} }
func (m *GetTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GetTimeResponse) ProtoMessage()    {}
func (*GetTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{3}
}
func (m *GetTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimeResponse.Unmarshal(m, b)
}
func (m *GetTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimeResponse.Marshal(b, m, deterministic)
}
func (m *GetTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimeResponse.Merge(m, src)
}
func (m *GetTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GetTimeResponse.Size(m)
}
func (m *GetTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimeResponse proto.InternalMessageInfo

func (m *GetTimeResponse) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

type ContactPingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactPingRequest) Reset()         { *m = ContactPingRequest{} }
func (m *ContactPingRequest) String() string { return proto.CompactTextString(m) }
func (*ContactPingRequest) ProtoMessage()    {}
func (*ContactPingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{4}
}
func (m *ContactPingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactPingRequest.Unmarshal(m, b)
}
func (m *ContactPingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactPingRequest.Marshal(b, m, deterministic)
}
func (m *ContactPingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactPingRequest.Merge(m, src)
}
func (m *ContactPingRequest) XXX_Size() int {
	return xxx_messageInfo_ContactPingRequest.Size(m)
}
func (m *ContactPingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactPingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContactPingRequest proto.InternalMessageInfo

type ContactPingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactPingResponse) Reset()         { *m = ContactPingResponse{} }
func (m *ContactPingResponse) String() string { return proto.CompactTextString(m) }
func (*ContactPingResponse) ProtoMessage()    {}
func (*ContactPingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{5}
}
func (m *ContactPingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactPingResponse.Unmarshal(m, b)
}
func (m *ContactPingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactPingResponse.Marshal(b, m, deterministic)
}
func (m *ContactPingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactPingResponse.Merge(m, src)
}
func (m *ContactPingResponse) XXX_Size() int {
	return xxx_messageInfo_ContactPingResponse.Size(m)
}
func (m *ContactPingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactPingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactPingResponse proto.InternalMessageInfo

type PingMeRequest struct {
	Address   string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Transport NodeTransport `protobuf:"varint,2,opt,name=transport,proto3,enum=node.NodeTransport" json:"transport,omitempty"`
	// PingMe may happen over TLS, which means there is not necessarily an
	// opportunity to use NoiseSessionAttestation instead of
	// NoiseKeyAttestation.
	NoiseKeyAttestation  *NoiseKeyAttestation `protobuf:"bytes,3,opt,name=noise_key_attestation,json=noiseKeyAttestation,proto3" json:"noise_key_attestation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PingMeRequest) Reset()         { *m = PingMeRequest{} }
func (m *PingMeRequest) String() string { return proto.CompactTextString(m) }
func (*PingMeRequest) ProtoMessage()    {}
func (*PingMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{6}
}
func (m *PingMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMeRequest.Unmarshal(m, b)
}
func (m *PingMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMeRequest.Marshal(b, m, deterministic)
}
func (m *PingMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMeRequest.Merge(m, src)
}
func (m *PingMeRequest) XXX_Size() int {
	return xxx_messageInfo_PingMeRequest.Size(m)
}
func (m *PingMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingMeRequest proto.InternalMessageInfo

func (m *PingMeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PingMeRequest) GetTransport() NodeTransport {
	if m != nil {
		return m.Transport
	}
	return NodeTransport_TCP_TLS_RPC
}

func (m *PingMeRequest) GetNoiseKeyAttestation() *NoiseKeyAttestation {
	if m != nil {
		return m.NoiseKeyAttestation
	}
	return nil
}

type PingMeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMeResponse) Reset()         { *m = PingMeResponse{} }
func (m *PingMeResponse) String() string { return proto.CompactTextString(m) }
func (*PingMeResponse) ProtoMessage()    {}
func (*PingMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{7}
}
func (m *PingMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMeResponse.Unmarshal(m, b)
}
func (m *PingMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMeResponse.Marshal(b, m, deterministic)
}
func (m *PingMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMeResponse.Merge(m, src)
}
func (m *PingMeResponse) XXX_Size() int {
	return xxx_messageInfo_PingMeResponse.Size(m)
}
func (m *PingMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingMeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CheckInRequest)(nil), "contact.CheckInRequest")
	proto.RegisterType((*CheckInResponse)(nil), "contact.CheckInResponse")
	proto.RegisterType((*GetTimeRequest)(nil), "contact.GetTimeRequest")
	proto.RegisterType((*GetTimeResponse)(nil), "contact.GetTimeResponse")
	proto.RegisterType((*ContactPingRequest)(nil), "contact.ContactPingRequest")
	proto.RegisterType((*ContactPingResponse)(nil), "contact.ContactPingResponse")
	proto.RegisterType((*PingMeRequest)(nil), "contact.PingMeRequest")
	proto.RegisterType((*PingMeResponse)(nil), "contact.PingMeResponse")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x4c,
	0x18, 0xfd, 0xfd, 0xf7, 0x62, 0xe7, 0xab, 0x9a, 0xb6, 0x93, 0x5e, 0x2c, 0x83, 0xd4, 0x28, 0x12,
	0x52, 0x04, 0xc8, 0x11, 0xed, 0x06, 0xa4, 0x6e, 0x68, 0x55, 0x21, 0x04, 0x2d, 0x65, 0x1a, 0x58,
	0xb0, 0xb1, 0x26, 0xce, 0xd4, 0x0c, 0xad, 0x67, 0x5c, 0xcf, 0x18, 0xa9, 0x7b, 0x1e, 0x80, 0x47,
	0xe0, 0x01, 0x78, 0x05, 0xf6, 0x3c, 0x05, 0xbc, 0x0a, 0x9a, 0x8b, 0x9d, 0x26, 0x01, 0x21, 0xb1,
	0x89, 0xf2, 0x9d, 0x73, 0xe6, 0xbb, 0x9e, 0x04, 0x56, 0x53, 0xc1, 0x15, 0x49, 0x55, 0x5c, 0x94,
	0x42, 0x09, 0xe4, 0xbb, 0x30, 0x82, 0x4c, 0x64, 0xc2, 0x82, 0xd1, 0x6e, 0x26, 0x44, 0x76, 0x45,
	0x07, 0x26, 0x1a, 0x55, 0x17, 0x03, 0xc5, 0x72, 0x2a, 0x15, 0xc9, 0x0b, 0x27, 0x00, 0x2e, 0xc6,
	0xd4, 0x7d, 0x5f, 0xe1, 0x82, 0xc9, 0x3a, 0x68, 0x6b, 0x42, 0x91, 0x4c, 0xda, 0xb8, 0xf7, 0x69,
	0x01, 0xda, 0x47, 0xef, 0x69, 0x7a, 0xf9, 0x9c, 0x63, 0x7a, 0x5d, 0x51, 0xa9, 0x50, 0x08, 0x3e,
	0x19, 0x8f, 0x4b, 0x2a, 0x65, 0xe8, 0x75, 0xbd, 0x7e, 0x0b, 0xd7, 0x21, 0x7a, 0x00, 0xfe, 0x47,
	0x5a, 0x4a, 0x26, 0x78, 0xf8, 0x7f, 0xd7, 0xeb, 0xaf, 0xec, 0x6d, 0xc4, 0xa6, 0xce, 0xa9, 0x18,
	0xd3, 0xb7, 0x96, 0xc0, 0xb5, 0x02, 0xc5, 0x10, 0xa4, 0xa4, 0x20, 0x29, 0x53, 0x37, 0xe1, 0x82,
	0x51, 0xa3, 0x89, 0xfa, 0xc8, 0x31, 0xb8, 0xd1, 0x68, 0xbd, 0x28, 0x68, 0x49, 0x94, 0x28, 0xc3,
	0xc5, 0x59, 0xfd, 0x2b, 0xc7, 0xe0, 0x46, 0x83, 0x4e, 0x61, 0xcb, 0x0c, 0x96, 0x5c, 0xd2, 0x9b,
	0x84, 0x28, 0xa5, 0xe7, 0x57, 0xba, 0xb5, 0x25, 0xf3, 0x38, 0x8a, 0xed, 0xd8, 0xa7, 0xfa, 0xf3,
	0x05, 0xbd, 0x79, 0x3a, 0x51, 0xe0, 0x0e, 0x9f, 0x07, 0xd1, 0x3d, 0x68, 0x8f, 0xe9, 0x48, 0x54,
	0x3c, 0xa5, 0xc9, 0x15, 0xcb, 0x99, 0x0a, 0x97, 0xbb, 0x5e, 0x7f, 0x09, 0xaf, 0xd6, 0xe8, 0x4b,
	0x0d, 0xa2, 0x08, 0x82, 0x0b, 0x4a, 0x54, 0x55, 0x52, 0x19, 0xfa, 0x5d, 0xaf, 0xbf, 0x88, 0x9b,
	0x18, 0x3d, 0x86, 0x15, 0xc9, 0x32, 0x4e, 0xc7, 0x89, 0xde, 0x70, 0x18, 0x98, 0x46, 0x76, 0xec,
	0x14, 0xe7, 0x86, 0xd0, 0xb3, 0x0c, 0x49, 0x76, 0x4e, 0x95, 0xc4, 0x60, 0xb5, 0x43, 0x92, 0xc9,
	0xde, 0x17, 0x0f, 0xd6, 0x9a, 0x33, 0xc8, 0x42, 0x70, 0x49, 0xd1, 0x7d, 0xd8, 0x28, 0x18, 0xcf,
	0x12, 0xfd, 0x3c, 0x91, 0x55, 0x9a, 0xd6, 0x17, 0x09, 0xf0, 0x9a, 0x26, 0x74, 0xae, 0x73, 0x0b,
	0xa3, 0x87, 0x80, 0x8c, 0x96, 0x96, 0xa5, 0x28, 0x93, 0x9c, 0x4a, 0x49, 0x32, 0x6a, 0x8e, 0xd4,
	0xc2, 0xeb, 0x9a, 0x39, 0xd6, 0xc4, 0x89, 0xc5, 0xd1, 0x3e, 0x6c, 0xcf, 0x65, 0x4e, 0xae, 0x2b,
	0x96, 0x9a, 0x43, 0x05, 0xb8, 0x33, 0x93, 0xfe, 0x75, 0xc5, 0xd2, 0xde, 0x3a, 0xb4, 0x9f, 0x51,
	0x35, 0x64, 0x39, 0x75, 0x46, 0xe9, 0xbd, 0x81, 0xb5, 0x06, 0x71, 0x3d, 0x1f, 0x42, 0xab, 0xb1,
	0xa2, 0xe9, 0x55, 0x1f, 0xc2, 0x9a, 0x35, 0xae, 0xcd, 0x1a, 0x0f, 0x6b, 0xc5, 0x61, 0xf0, 0xfd,
	0xc7, 0xee, 0x7f, 0x9f, 0x7f, 0xee, 0x7a, 0x78, 0xf2, 0xac, 0xb7, 0x09, 0xe8, 0xc8, 0x7a, 0xfe,
	0x8c, 0xf1, 0xac, 0x2e, 0xb6, 0x05, 0x9d, 0x29, 0xd4, 0x16, 0xec, 0x7d, 0xf5, 0x60, 0x55, 0x03,
	0x27, 0xf4, 0xef, 0xf6, 0x7d, 0x04, 0x2d, 0x55, 0x12, 0x2e, 0x0b, 0x51, 0x2a, 0xb3, 0x9b, 0xf6,
	0x5e, 0x67, 0x62, 0xb1, 0x61, 0x4d, 0xe1, 0x89, 0xea, 0xcf, 0x26, 0x5b, 0xf8, 0x27, 0x93, 0xe9,
	0x25, 0xd6, 0xdd, 0xda, 0x01, 0xf6, 0xce, 0xc0, 0x77, 0x73, 0xa1, 0x63, 0x08, 0xce, 0xdc, 0xe2,
	0xd1, 0x9d, 0xb8, 0xfe, 0x1b, 0x98, 0xdf, 0x45, 0x74, 0xf7, 0xf7, 0xa4, 0xcb, 0xf8, 0xcd, 0x83,
	0x45, 0x93, 0xe3, 0x00, 0x7c, 0xe7, 0x29, 0xb4, 0x33, 0x79, 0x31, 0xf5, 0x63, 0x8f, 0xc2, 0x79,
	0xc2, 0x9d, 0xf2, 0x09, 0x2c, 0xdb, 0x56, 0xd1, 0x76, 0xa3, 0x99, 0xda, 0x74, 0xb4, 0x33, 0x87,
	0xbb, 0xa7, 0x07, 0xe0, 0x3b, 0x63, 0xdc, 0x2a, 0x3c, 0x6d, 0x9e, 0x5b, 0x85, 0x67, 0x3c, 0x74,
	0xb8, 0xf9, 0x0e, 0x49, 0x25, 0xca, 0x0f, 0x31, 0x13, 0x83, 0x54, 0xe4, 0xb9, 0xe0, 0x83, 0x62,
	0x34, 0x5a, 0x36, 0xf6, 0xd9, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa5, 0xfe, 0xbf, 0x1f,
	0x05, 0x00, 0x00,
}
