// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: encryption_access.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EncryptionAccess struct {
	DefaultKey                  []byte                         `protobuf:"bytes,1,opt,name=default_key,json=defaultKey,proto3" json:"default_key,omitempty"`
	StoreEntries                []*EncryptionAccess_StoreEntry `protobuf:"bytes,2,rep,name=store_entries,json=storeEntries,proto3" json:"store_entries,omitempty"`
	DefaultPathCipher           CipherSuite                    `protobuf:"varint,3,opt,name=default_path_cipher,json=defaultPathCipher,proto3,enum=encryption.CipherSuite" json:"default_path_cipher,omitempty"`
	DefaultEncryptionParameters *EncryptionParameters          `protobuf:"bytes,4,opt,name=default_encryption_parameters,json=defaultEncryptionParameters,proto3" json:"default_encryption_parameters,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                       `json:"-"`
	XXX_unrecognized            []byte                         `json:"-"`
	XXX_sizecache               int32                          `json:"-"`
}

func (m *EncryptionAccess) Reset()         { *m = EncryptionAccess{} }
func (m *EncryptionAccess) String() string { return proto.CompactTextString(m) }
func (*EncryptionAccess) ProtoMessage()    {}
func (*EncryptionAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b1a18bff4a17b, []int{0}
}
func (m *EncryptionAccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionAccess.Unmarshal(m, b)
}
func (m *EncryptionAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionAccess.Marshal(b, m, deterministic)
}
func (m *EncryptionAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionAccess.Merge(m, src)
}
func (m *EncryptionAccess) XXX_Size() int {
	return xxx_messageInfo_EncryptionAccess.Size(m)
}
func (m *EncryptionAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionAccess.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionAccess proto.InternalMessageInfo

func (m *EncryptionAccess) GetDefaultKey() []byte {
	if m != nil {
		return m.DefaultKey
	}
	return nil
}

func (m *EncryptionAccess) GetStoreEntries() []*EncryptionAccess_StoreEntry {
	if m != nil {
		return m.StoreEntries
	}
	return nil
}

func (m *EncryptionAccess) GetDefaultPathCipher() CipherSuite {
	if m != nil {
		return m.DefaultPathCipher
	}
	return CipherSuite_ENC_UNSPECIFIED
}

func (m *EncryptionAccess) GetDefaultEncryptionParameters() *EncryptionParameters {
	if m != nil {
		return m.DefaultEncryptionParameters
	}
	return nil
}

type EncryptionAccess_StoreEntry struct {
	Bucket               []byte                `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	UnencryptedPath      []byte                `protobuf:"bytes,2,opt,name=unencrypted_path,json=unencryptedPath,proto3" json:"unencrypted_path,omitempty"`
	EncryptedPath        []byte                `protobuf:"bytes,3,opt,name=encrypted_path,json=encryptedPath,proto3" json:"encrypted_path,omitempty"`
	Key                  []byte                `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	PathCipher           CipherSuite           `protobuf:"varint,5,opt,name=path_cipher,json=pathCipher,proto3,enum=encryption.CipherSuite" json:"path_cipher,omitempty"`
	EncryptionParameters *EncryptionParameters `protobuf:"bytes,6,opt,name=encryption_parameters,json=encryptionParameters,proto3" json:"encryption_parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EncryptionAccess_StoreEntry) Reset()         { *m = EncryptionAccess_StoreEntry{} }
func (m *EncryptionAccess_StoreEntry) String() string { return proto.CompactTextString(m) }
func (*EncryptionAccess_StoreEntry) ProtoMessage()    {}
func (*EncryptionAccess_StoreEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_464b1a18bff4a17b, []int{0, 0}
}
func (m *EncryptionAccess_StoreEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptionAccess_StoreEntry.Unmarshal(m, b)
}
func (m *EncryptionAccess_StoreEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptionAccess_StoreEntry.Marshal(b, m, deterministic)
}
func (m *EncryptionAccess_StoreEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptionAccess_StoreEntry.Merge(m, src)
}
func (m *EncryptionAccess_StoreEntry) XXX_Size() int {
	return xxx_messageInfo_EncryptionAccess_StoreEntry.Size(m)
}
func (m *EncryptionAccess_StoreEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptionAccess_StoreEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptionAccess_StoreEntry proto.InternalMessageInfo

func (m *EncryptionAccess_StoreEntry) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *EncryptionAccess_StoreEntry) GetUnencryptedPath() []byte {
	if m != nil {
		return m.UnencryptedPath
	}
	return nil
}

func (m *EncryptionAccess_StoreEntry) GetEncryptedPath() []byte {
	if m != nil {
		return m.EncryptedPath
	}
	return nil
}

func (m *EncryptionAccess_StoreEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EncryptionAccess_StoreEntry) GetPathCipher() CipherSuite {
	if m != nil {
		return m.PathCipher
	}
	return CipherSuite_ENC_UNSPECIFIED
}

func (m *EncryptionAccess_StoreEntry) GetEncryptionParameters() *EncryptionParameters {
	if m != nil {
		return m.EncryptionParameters
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptionAccess)(nil), "encryption_access.EncryptionAccess")
	proto.RegisterType((*EncryptionAccess_StoreEntry)(nil), "encryption_access.EncryptionAccess.StoreEntry")
}

func init() { proto.RegisterFile("encryption_access.proto", fileDescriptor_464b1a18bff4a17b) }

var fileDescriptor_464b1a18bff4a17b = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x14, 0x0c, 0x1f, 0xf6, 0xf0, 0x68, 0x2b, 0x5d, 0x3f, 0x4a, 0x6a, 0x8c, 0xc4, 0xc4, 0x04, 0x2f,
	0x1c, 0xea, 0xc5, 0xab, 0x9a, 0xc6, 0x83, 0x97, 0x86, 0xc6, 0x8b, 0x17, 0xb2, 0xa5, 0xcf, 0x94,
	0x54, 0x61, 0xb3, 0xbb, 0x1c, 0xf8, 0x29, 0xfe, 0x2e, 0xff, 0x90, 0x61, 0xbb, 0x14, 0x6c, 0x89,
	0xf1, 0xb6, 0xcc, 0xcc, 0xce, 0x9b, 0x37, 0x2c, 0x8c, 0x31, 0x4b, 0x78, 0xc9, 0x64, 0x9a, 0x67,
	0x31, 0x4d, 0x12, 0x14, 0x22, 0x64, 0x3c, 0x97, 0x39, 0x19, 0x1d, 0x10, 0x13, 0xb7, 0x81, 0xb6,
	0xa2, 0xeb, 0x6f, 0x1b, 0xdc, 0xd9, 0x0e, 0x7c, 0x50, 0x32, 0x72, 0x05, 0xce, 0x0a, 0xdf, 0x69,
	0xf1, 0x21, 0xe3, 0x0d, 0x96, 0x9e, 0xe1, 0x1b, 0x41, 0x3f, 0x02, 0x0d, 0xbd, 0x60, 0x49, 0x16,
	0x30, 0x10, 0x32, 0xe7, 0x18, 0x63, 0x26, 0x79, 0x8a, 0xc2, 0x33, 0x7d, 0x2b, 0x70, 0xa6, 0x61,
	0x78, 0x98, 0x65, 0xdf, 0x3c, 0x5c, 0x54, 0x17, 0x67, 0x99, 0xe4, 0x65, 0xd4, 0x17, 0xf5, 0x39,
	0x45, 0x41, 0x9e, 0xe1, 0xa4, 0x9e, 0xca, 0xa8, 0x5c, 0xc7, 0x49, 0xca, 0xd6, 0xc8, 0x3d, 0xcb,
	0x37, 0x82, 0xe1, 0x74, 0xdc, 0xb2, 0x0e, 0x9f, 0x14, 0xb3, 0x28, 0x52, 0x89, 0xd1, 0x48, 0xdf,
	0x99, 0x53, 0xb9, 0xde, 0xe2, 0x64, 0x05, 0x97, 0xb5, 0x51, 0x2b, 0x0f, 0xa3, 0x9c, 0x7e, 0xa2,
	0x44, 0x2e, 0x3c, 0xdb, 0x37, 0x02, 0x67, 0xea, 0xb7, 0x2d, 0x9b, 0x98, 0xf3, 0x9d, 0x2e, 0xba,
	0xd0, 0x36, 0x5d, 0xe4, 0xe4, 0xcb, 0x04, 0x68, 0x76, 0x21, 0xe7, 0xd0, 0x5b, 0x16, 0xc9, 0x06,
	0xa5, 0xae, 0x4b, 0x7f, 0x91, 0x5b, 0x70, 0x8b, 0x4c, 0x0f, 0xc2, 0x95, 0xda, 0xcc, 0x33, 0x95,
	0xe2, 0xb8, 0x85, 0x57, 0xe9, 0xc9, 0x0d, 0x0c, 0xf7, 0x84, 0x96, 0x12, 0x0e, 0x7e, 0xcb, 0x5c,
	0xb0, 0xaa, 0xbf, 0x62, 0x2b, 0xae, 0x3a, 0x92, 0x7b, 0x70, 0xda, 0x8d, 0x1d, 0xfd, 0xdd, 0x18,
	0xb0, 0xa6, 0xaa, 0x57, 0x38, 0xeb, 0xae, 0xa8, 0xf7, 0xcf, 0x8a, 0x4e, 0xb1, 0x03, 0x7d, 0xb4,
	0xdf, 0x4c, 0xb6, 0x5c, 0xf6, 0xd4, 0x13, 0xbb, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x07, 0xd7,
	0xa5, 0xd0, 0xa2, 0x02, 0x00, 0x00,
}
