// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heldamount.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"

	drpc "storj.io/drpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetHeldAmountRequest struct {
	Period               time.Time `protobuf:"bytes,1,opt,name=period,proto3,stdtime" json:"period"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHeldAmountRequest) Reset()         { *m = GetHeldAmountRequest{} }
func (m *GetHeldAmountRequest) String() string { return proto.CompactTextString(m) }
func (*GetHeldAmountRequest) ProtoMessage()    {}
func (*GetHeldAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{0}
}
func (m *GetHeldAmountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeldAmountRequest.Unmarshal(m, b)
}
func (m *GetHeldAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeldAmountRequest.Marshal(b, m, deterministic)
}
func (m *GetHeldAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeldAmountRequest.Merge(m, src)
}
func (m *GetHeldAmountRequest) XXX_Size() int {
	return xxx_messageInfo_GetHeldAmountRequest.Size(m)
}
func (m *GetHeldAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeldAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeldAmountRequest proto.InternalMessageInfo

func (m *GetHeldAmountRequest) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

type GetHeldAmountResponse struct {
	Period               time.Time `protobuf:"bytes,1,opt,name=period,proto3,stdtime" json:"period"`
	NodeId               NodeID    `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	CreatedAt            time.Time `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	Codes                string    `protobuf:"bytes,4,opt,name=codes,proto3" json:"codes,omitempty"`
	UsageAtRest          float32   `protobuf:"fixed32,5,opt,name=usage_at_rest,json=usageAtRest,proto3" json:"usage_at_rest,omitempty"`
	UsageGet             int64     `protobuf:"varint,6,opt,name=usage_get,json=usageGet,proto3" json:"usage_get,omitempty"`
	UsagePut             int64     `protobuf:"varint,7,opt,name=usage_put,json=usagePut,proto3" json:"usage_put,omitempty"`
	UsageGetRepair       int64     `protobuf:"varint,8,opt,name=usage_get_repair,json=usageGetRepair,proto3" json:"usage_get_repair,omitempty"`
	UsagePutRepair       int64     `protobuf:"varint,9,opt,name=usage_put_repair,json=usagePutRepair,proto3" json:"usage_put_repair,omitempty"`
	UsageGetAudit        int64     `protobuf:"varint,10,opt,name=usage_get_audit,json=usageGetAudit,proto3" json:"usage_get_audit,omitempty"`
	CompAtRest           int64     `protobuf:"varint,11,opt,name=comp_at_rest,json=compAtRest,proto3" json:"comp_at_rest,omitempty"`
	CompGet              int64     `protobuf:"varint,12,opt,name=comp_get,json=compGet,proto3" json:"comp_get,omitempty"`
	CompPut              int64     `protobuf:"varint,13,opt,name=comp_put,json=compPut,proto3" json:"comp_put,omitempty"`
	CompGetRepair        int64     `protobuf:"varint,14,opt,name=comp_get_repair,json=compGetRepair,proto3" json:"comp_get_repair,omitempty"`
	CompPutRepair        int64     `protobuf:"varint,15,opt,name=comp_put_repair,json=compPutRepair,proto3" json:"comp_put_repair,omitempty"`
	CompGetAudit         int64     `protobuf:"varint,16,opt,name=comp_get_audit,json=compGetAudit,proto3" json:"comp_get_audit,omitempty"`
	SurgePercent         int64     `protobuf:"varint,17,opt,name=surge_percent,json=surgePercent,proto3" json:"surge_percent,omitempty"`
	Held                 int64     `protobuf:"varint,18,opt,name=held,proto3" json:"held,omitempty"`
	Owed                 int64     `protobuf:"varint,19,opt,name=owed,proto3" json:"owed,omitempty"`
	Disposed             int64     `protobuf:"varint,20,opt,name=disposed,proto3" json:"disposed,omitempty"`
	Paid                 int64     `protobuf:"varint,21,opt,name=paid,proto3" json:"paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHeldAmountResponse) Reset()         { *m = GetHeldAmountResponse{} }
func (m *GetHeldAmountResponse) String() string { return proto.CompactTextString(m) }
func (*GetHeldAmountResponse) ProtoMessage()    {}
func (*GetHeldAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{1}
}
func (m *GetHeldAmountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeldAmountResponse.Unmarshal(m, b)
}
func (m *GetHeldAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeldAmountResponse.Marshal(b, m, deterministic)
}
func (m *GetHeldAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeldAmountResponse.Merge(m, src)
}
func (m *GetHeldAmountResponse) XXX_Size() int {
	return xxx_messageInfo_GetHeldAmountResponse.Size(m)
}
func (m *GetHeldAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeldAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeldAmountResponse proto.InternalMessageInfo

func (m *GetHeldAmountResponse) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

func (m *GetHeldAmountResponse) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *GetHeldAmountResponse) GetCodes() string {
	if m != nil {
		return m.Codes
	}
	return ""
}

func (m *GetHeldAmountResponse) GetUsageAtRest() float32 {
	if m != nil {
		return m.UsageAtRest
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGet() int64 {
	if m != nil {
		return m.UsageGet
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsagePut() int64 {
	if m != nil {
		return m.UsagePut
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGetRepair() int64 {
	if m != nil {
		return m.UsageGetRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsagePutRepair() int64 {
	if m != nil {
		return m.UsagePutRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGetAudit() int64 {
	if m != nil {
		return m.UsageGetAudit
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompAtRest() int64 {
	if m != nil {
		return m.CompAtRest
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGet() int64 {
	if m != nil {
		return m.CompGet
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompPut() int64 {
	if m != nil {
		return m.CompPut
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGetRepair() int64 {
	if m != nil {
		return m.CompGetRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompPutRepair() int64 {
	if m != nil {
		return m.CompPutRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGetAudit() int64 {
	if m != nil {
		return m.CompGetAudit
	}
	return 0
}

func (m *GetHeldAmountResponse) GetSurgePercent() int64 {
	if m != nil {
		return m.SurgePercent
	}
	return 0
}

func (m *GetHeldAmountResponse) GetHeld() int64 {
	if m != nil {
		return m.Held
	}
	return 0
}

func (m *GetHeldAmountResponse) GetOwed() int64 {
	if m != nil {
		return m.Owed
	}
	return 0
}

func (m *GetHeldAmountResponse) GetDisposed() int64 {
	if m != nil {
		return m.Disposed
	}
	return 0
}

func (m *GetHeldAmountResponse) GetPaid() int64 {
	if m != nil {
		return m.Paid
	}
	return 0
}

type GetAllPaystubsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPaystubsRequest) Reset()         { *m = GetAllPaystubsRequest{} }
func (m *GetAllPaystubsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPaystubsRequest) ProtoMessage()    {}
func (*GetAllPaystubsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{2}
}
func (m *GetAllPaystubsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaystubsRequest.Unmarshal(m, b)
}
func (m *GetAllPaystubsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaystubsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPaystubsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaystubsRequest.Merge(m, src)
}
func (m *GetAllPaystubsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPaystubsRequest.Size(m)
}
func (m *GetAllPaystubsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaystubsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaystubsRequest proto.InternalMessageInfo

type GetAllPaystubsResponse struct {
	Paystub              []*GetHeldAmountResponse `protobuf:"bytes,1,rep,name=paystub,proto3" json:"paystub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetAllPaystubsResponse) Reset()         { *m = GetAllPaystubsResponse{} }
func (m *GetAllPaystubsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPaystubsResponse) ProtoMessage()    {}
func (*GetAllPaystubsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{3}
}
func (m *GetAllPaystubsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaystubsResponse.Unmarshal(m, b)
}
func (m *GetAllPaystubsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaystubsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPaystubsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaystubsResponse.Merge(m, src)
}
func (m *GetAllPaystubsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPaystubsResponse.Size(m)
}
func (m *GetAllPaystubsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaystubsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaystubsResponse proto.InternalMessageInfo

func (m *GetAllPaystubsResponse) GetPaystub() []*GetHeldAmountResponse {
	if m != nil {
		return m.Paystub
	}
	return nil
}

type GetPaymentRequest struct {
	Period               time.Time `protobuf:"bytes,1,opt,name=period,proto3,stdtime" json:"period"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPaymentRequest) Reset()         { *m = GetPaymentRequest{} }
func (m *GetPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*GetPaymentRequest) ProtoMessage()    {}
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{4}
}
func (m *GetPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentRequest.Unmarshal(m, b)
}
func (m *GetPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentRequest.Marshal(b, m, deterministic)
}
func (m *GetPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentRequest.Merge(m, src)
}
func (m *GetPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_GetPaymentRequest.Size(m)
}
func (m *GetPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentRequest proto.InternalMessageInfo

func (m *GetPaymentRequest) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

type GetPaymentResponse struct {
	NodeId               NodeID    `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	CreatedAt            time.Time `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	Period               time.Time `protobuf:"bytes,3,opt,name=period,proto3,stdtime" json:"period"`
	Amount               int64     `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Receipt              string    `protobuf:"bytes,5,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Notes                string    `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	Id                   int64     `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPaymentResponse) Reset()         { *m = GetPaymentResponse{} }
func (m *GetPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*GetPaymentResponse) ProtoMessage()    {}
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{5}
}
func (m *GetPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentResponse.Unmarshal(m, b)
}
func (m *GetPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentResponse.Marshal(b, m, deterministic)
}
func (m *GetPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentResponse.Merge(m, src)
}
func (m *GetPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_GetPaymentResponse.Size(m)
}
func (m *GetPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentResponse proto.InternalMessageInfo

func (m *GetPaymentResponse) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *GetPaymentResponse) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

func (m *GetPaymentResponse) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetPaymentResponse) GetReceipt() string {
	if m != nil {
		return m.Receipt
	}
	return ""
}

func (m *GetPaymentResponse) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *GetPaymentResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllPaymentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPaymentsRequest) Reset()         { *m = GetAllPaymentsRequest{} }
func (m *GetAllPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPaymentsRequest) ProtoMessage()    {}
func (*GetAllPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{6}
}
func (m *GetAllPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaymentsRequest.Unmarshal(m, b)
}
func (m *GetAllPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaymentsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaymentsRequest.Merge(m, src)
}
func (m *GetAllPaymentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPaymentsRequest.Size(m)
}
func (m *GetAllPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaymentsRequest proto.InternalMessageInfo

type GetAllPaymentsResponse struct {
	Payment              []*GetPaymentResponse `protobuf:"bytes,1,rep,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAllPaymentsResponse) Reset()         { *m = GetAllPaymentsResponse{} }
func (m *GetAllPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPaymentsResponse) ProtoMessage()    {}
func (*GetAllPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{7}
}
func (m *GetAllPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaymentsResponse.Unmarshal(m, b)
}
func (m *GetAllPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaymentsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaymentsResponse.Merge(m, src)
}
func (m *GetAllPaymentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPaymentsResponse.Size(m)
}
func (m *GetAllPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaymentsResponse proto.InternalMessageInfo

func (m *GetAllPaymentsResponse) GetPayment() []*GetPaymentResponse {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*GetHeldAmountRequest)(nil), "heldamount.GetHeldAmountRequest")
	proto.RegisterType((*GetHeldAmountResponse)(nil), "heldamount.GetHeldAmountResponse")
	proto.RegisterType((*GetAllPaystubsRequest)(nil), "heldamount.GetAllPaystubsRequest")
	proto.RegisterType((*GetAllPaystubsResponse)(nil), "heldamount.GetAllPaystubsResponse")
	proto.RegisterType((*GetPaymentRequest)(nil), "heldamount.GetPaymentRequest")
	proto.RegisterType((*GetPaymentResponse)(nil), "heldamount.GetPaymentResponse")
	proto.RegisterType((*GetAllPaymentsRequest)(nil), "heldamount.GetAllPaymentsRequest")
	proto.RegisterType((*GetAllPaymentsResponse)(nil), "heldamount.GetAllPaymentsResponse")
}

func init() { proto.RegisterFile("heldamount.proto", fileDescriptor_5c5d9f6e3ee97993) }

var fileDescriptor_5c5d9f6e3ee97993 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x9b, 0x9f, 0xc9, 0x4f, 0xdb, 0x25, 0x2d, 0x4b, 0x10, 0xc4, 0x04, 0x54, 0x72,
	0x4a, 0xa4, 0x72, 0x41, 0x82, 0x4b, 0x0a, 0x52, 0xa9, 0x90, 0x50, 0x6a, 0x8a, 0x90, 0xb8, 0x44,
	0x4e, 0x76, 0x08, 0x46, 0x71, 0xd6, 0xd8, 0x6b, 0xa1, 0xbe, 0x05, 0x47, 0x1e, 0x89, 0x67, 0xe0,
	0x50, 0xde, 0x04, 0xa1, 0xfd, 0x8b, 0xdd, 0x40, 0x5b, 0xb5, 0x70, 0xf3, 0xcc, 0x7c, 0xf3, 0x65,
	0xbe, 0x99, 0xfd, 0x02, 0x9b, 0x1f, 0x71, 0xce, 0xfc, 0x90, 0xa7, 0x0b, 0xd1, 0x8f, 0x62, 0x2e,
	0x38, 0x81, 0x2c, 0xd3, 0x86, 0x19, 0x9f, 0x71, 0x9d, 0x6f, 0x77, 0x66, 0x9c, 0xcf, 0xe6, 0x38,
	0x50, 0xd1, 0x24, 0xfd, 0x30, 0x10, 0x41, 0x88, 0x89, 0xf0, 0xc3, 0x48, 0x03, 0xba, 0xc7, 0xd0,
	0x3a, 0x40, 0xf1, 0x12, 0xe7, 0x6c, 0xa8, 0xba, 0x3d, 0xfc, 0x9c, 0x62, 0x22, 0xc8, 0x33, 0x28,
	0x45, 0x18, 0x07, 0x9c, 0x51, 0xc7, 0x75, 0x7a, 0xb5, 0xbd, 0x76, 0x5f, 0x33, 0xf5, 0x2d, 0x53,
	0xff, 0xd8, 0x32, 0xed, 0x57, 0xbe, 0x9f, 0x76, 0x6e, 0x7c, 0xfd, 0xd9, 0x71, 0x3c, 0xd3, 0xd3,
	0xfd, 0xb5, 0x0e, 0xdb, 0x2b, 0xb4, 0x49, 0xc4, 0x17, 0x09, 0xfe, 0x1b, 0x2f, 0x79, 0x04, 0xe5,
	0x05, 0x67, 0x38, 0x0e, 0x18, 0x2d, 0xb8, 0x4e, 0xaf, 0xbe, 0xdf, 0x94, 0x90, 0x1f, 0xa7, 0x9d,
	0xd2, 0x6b, 0xce, 0xf0, 0xf0, 0x85, 0x57, 0x92, 0xe5, 0x43, 0x46, 0x9e, 0x03, 0x4c, 0x63, 0xf4,
	0x05, 0xb2, 0xb1, 0x2f, 0x68, 0xf1, 0x0a, 0x3f, 0x55, 0x35, 0x7d, 0x43, 0x41, 0x5a, 0xb0, 0x3e,
	0xe5, 0x0c, 0x13, 0xba, 0xe6, 0x3a, 0xbd, 0xaa, 0xa7, 0x03, 0xd2, 0x85, 0x46, 0x9a, 0xf8, 0x33,
	0x1c, 0xfb, 0x62, 0x1c, 0x63, 0x22, 0xe8, 0xba, 0xeb, 0xf4, 0x0a, 0x5e, 0x4d, 0x25, 0x87, 0x52,
	0xa9, 0x20, 0x77, 0xa0, 0xaa, 0x31, 0x33, 0x14, 0xb4, 0xe4, 0x3a, 0xbd, 0xa2, 0x57, 0x51, 0x89,
	0x03, 0xcc, 0x15, 0xa3, 0x54, 0xd0, 0x72, 0xae, 0x38, 0x4a, 0x05, 0xe9, 0xc1, 0xe6, 0xb2, 0x73,
	0x1c, 0x63, 0xe4, 0x07, 0x31, 0xad, 0x28, 0x4c, 0xd3, 0x12, 0x78, 0x2a, 0x9b, 0x21, 0xa3, 0x74,
	0x89, 0xac, 0xe6, 0x90, 0xa3, 0xd4, 0x22, 0x77, 0x61, 0x23, 0xe3, 0xf4, 0x53, 0x16, 0x08, 0x0a,
	0x0a, 0xd8, 0xb0, 0x94, 0x43, 0x99, 0x24, 0x2e, 0xd4, 0xa7, 0x3c, 0x8c, 0x96, 0xc2, 0x6a, 0x0a,
	0x04, 0x32, 0x67, 0x74, 0xdd, 0x86, 0x8a, 0x42, 0x48, 0x59, 0x75, 0x55, 0x2d, 0xcb, 0x58, 0xaa,
	0xb2, 0x25, 0x29, 0xaa, 0x91, 0x95, 0xa4, 0xa6, 0x5d, 0xd8, 0xb0, 0x5d, 0x76, 0xd0, 0xa6, 0xfe,
	0x7d, 0xd3, 0x9c, 0xcd, 0x69, 0x29, 0x2c, 0x6e, 0x23, 0xc3, 0x65, 0x7a, 0x1e, 0x42, 0x73, 0xc9,
	0xa7, 0xe5, 0x6c, 0x2a, 0x58, 0xdd, 0xd0, 0x69, 0x35, 0x0f, 0xa0, 0x91, 0xa4, 0xb1, 0xdc, 0x0f,
	0xc6, 0x53, 0x5c, 0x08, 0xba, 0xa5, 0x41, 0x2a, 0x39, 0xd2, 0x39, 0x42, 0x60, 0x4d, 0x3a, 0x87,
	0x12, 0x55, 0x53, 0xdf, 0x32, 0xc7, 0xbf, 0x20, 0xa3, 0x37, 0x75, 0x4e, 0x7e, 0x93, 0x36, 0x54,
	0x58, 0x90, 0x44, 0x3c, 0x41, 0x46, 0x5b, 0xfa, 0x64, 0x36, 0x96, 0xf8, 0xc8, 0x0f, 0x18, 0xdd,
	0xd6, 0x78, 0xf9, 0xdd, 0xbd, 0xa5, 0xde, 0xff, 0x70, 0x3e, 0x1f, 0xf9, 0x27, 0x89, 0x48, 0x27,
	0x89, 0xf1, 0x55, 0xf7, 0x2d, 0xec, 0xac, 0x16, 0x8c, 0x33, 0x9e, 0x42, 0x39, 0xd2, 0x39, 0xea,
	0xb8, 0xc5, 0x5e, 0x6d, 0xef, 0x7e, 0x3f, 0x67, 0xf3, 0xbf, 0xba, 0xc9, 0xb3, 0x1d, 0xdd, 0x23,
	0xd8, 0x3a, 0x40, 0x31, 0xf2, 0x4f, 0x42, 0xfc, 0x5f, 0x1e, 0xfe, 0x56, 0x00, 0x92, 0xe7, 0x34,
	0x63, 0xe6, 0x2c, 0xe8, 0x5c, 0xc1, 0x82, 0x85, 0xeb, 0x59, 0x30, 0x93, 0x50, 0xbc, 0xc6, 0xdf,
	0xc5, 0x0e, 0x94, 0xf4, 0xfa, 0x94, 0x83, 0x8b, 0x9e, 0x89, 0x08, 0x85, 0x72, 0x8c, 0x53, 0x0c,
	0x22, 0x6d, 0xde, 0xaa, 0x67, 0x43, 0x69, 0xf9, 0x05, 0x17, 0x98, 0x28, 0xd3, 0x56, 0x3d, 0x1d,
	0x90, 0x26, 0x14, 0x02, 0x66, 0xac, 0x5a, 0x58, 0xb9, 0xae, 0x5c, 0xce, 0xf2, 0xba, 0x5e, 0xee,
	0xba, 0xa6, 0x60, 0xd6, 0xf6, 0x44, 0x5d, 0x57, 0xe6, 0xcc, 0x75, 0xef, 0xad, 0x5c, 0x77, 0x65,
	0xcf, 0x9e, 0x85, 0xef, 0x9d, 0x16, 0x00, 0xb2, 0xd3, 0x93, 0x23, 0x00, 0x8d, 0x7e, 0x23, 0xd2,
	0x09, 0x71, 0x2f, 0x78, 0x23, 0x6a, 0xa4, 0xf6, 0xe5, 0xaf, 0x88, 0xbc, 0x83, 0xe6, 0xd9, 0x37,
	0x49, 0x56, 0x9b, 0xfe, 0x7c, 0xc8, 0xed, 0xee, 0x45, 0x10, 0x43, 0xfc, 0xca, 0xce, 0x2a, 0x85,
	0x90, 0xbb, 0xe7, 0x29, 0xd6, 0x84, 0x97, 0x2c, 0xe4, 0xcc, 0x94, 0x6a, 0xb7, 0xe7, 0x4c, 0x99,
	0x3f, 0xc8, 0x39, 0x53, 0x9e, 0x39, 0xcd, 0x7e, 0xeb, 0x3d, 0x49, 0x04, 0x8f, 0x3f, 0xf5, 0x03,
	0x3e, 0x98, 0xf2, 0x30, 0xe4, 0x8b, 0x41, 0x34, 0x99, 0x94, 0xd4, 0x0b, 0x7b, 0xfc, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0x38, 0x88, 0x98, 0x6c, 0x07, 0x00, 0x00,
}

// --- DRPC BEGIN ---

type DRPCHeldAmountClient interface {
	DRPCConn() drpc.Conn

	GetPayStub(ctx context.Context, in *GetHeldAmountRequest) (*GetHeldAmountResponse, error)
	GetAllPaystubs(ctx context.Context, in *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest) (*GetPaymentResponse, error)
	GetAllPayments(ctx context.Context, in *GetAllPaymentsRequest) (*GetAllPaymentsResponse, error)
}

type drpcHeldAmountClient struct {
	cc drpc.Conn
}

func NewDRPCHeldAmountClient(cc drpc.Conn) DRPCHeldAmountClient {
	return &drpcHeldAmountClient{cc}
}

func (c *drpcHeldAmountClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcHeldAmountClient) GetPayStub(ctx context.Context, in *GetHeldAmountRequest) (*GetHeldAmountResponse, error) {
	out := new(GetHeldAmountResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetPayStub", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcHeldAmountClient) GetAllPaystubs(ctx context.Context, in *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error) {
	out := new(GetAllPaystubsResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetAllPaystubs", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcHeldAmountClient) GetPayment(ctx context.Context, in *GetPaymentRequest) (*GetPaymentResponse, error) {
	out := new(GetPaymentResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetPayment", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcHeldAmountClient) GetAllPayments(ctx context.Context, in *GetAllPaymentsRequest) (*GetAllPaymentsResponse, error) {
	out := new(GetAllPaymentsResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetAllPayments", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCHeldAmountServer interface {
	GetPayStub(context.Context, *GetHeldAmountRequest) (*GetHeldAmountResponse, error)
	GetAllPaystubs(context.Context, *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentResponse, error)
	GetAllPayments(context.Context, *GetAllPaymentsRequest) (*GetAllPaymentsResponse, error)
}

type DRPCHeldAmountDescription struct{}

func (DRPCHeldAmountDescription) NumMethods() int { return 4 }

func (DRPCHeldAmountDescription) Method(n int) (string, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/heldamount.HeldAmount/GetPayStub",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetPayStub(
						ctx,
						in1.(*GetHeldAmountRequest),
					)
			}, DRPCHeldAmountServer.GetPayStub, true
	case 1:
		return "/heldamount.HeldAmount/GetAllPaystubs",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetAllPaystubs(
						ctx,
						in1.(*GetAllPaystubsRequest),
					)
			}, DRPCHeldAmountServer.GetAllPaystubs, true
	case 2:
		return "/heldamount.HeldAmount/GetPayment",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetPayment(
						ctx,
						in1.(*GetPaymentRequest),
					)
			}, DRPCHeldAmountServer.GetPayment, true
	case 3:
		return "/heldamount.HeldAmount/GetAllPayments",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetAllPayments(
						ctx,
						in1.(*GetAllPaymentsRequest),
					)
			}, DRPCHeldAmountServer.GetAllPayments, true
	default:
		return "", nil, nil, false
	}
}

func DRPCRegisterHeldAmount(mux drpc.Mux, impl DRPCHeldAmountServer) error {
	return mux.Register(impl, DRPCHeldAmountDescription{})
}

type DRPCHeldAmount_GetPayStubStream interface {
	drpc.Stream
	SendAndClose(*GetHeldAmountResponse) error
}

type drpcHeldAmountGetPayStubStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetPayStubStream) SendAndClose(m *GetHeldAmountResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCHeldAmount_GetAllPaystubsStream interface {
	drpc.Stream
	SendAndClose(*GetAllPaystubsResponse) error
}

type drpcHeldAmountGetAllPaystubsStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetAllPaystubsStream) SendAndClose(m *GetAllPaystubsResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCHeldAmount_GetPaymentStream interface {
	drpc.Stream
	SendAndClose(*GetPaymentResponse) error
}

type drpcHeldAmountGetPaymentStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetPaymentStream) SendAndClose(m *GetPaymentResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCHeldAmount_GetAllPaymentsStream interface {
	drpc.Stream
	SendAndClose(*GetAllPaymentsResponse) error
}

type drpcHeldAmountGetAllPaymentsStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetAllPaymentsStream) SendAndClose(m *GetAllPaymentsResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

// --- DRPC END ---
