// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heldamount.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"

	drpc "storj.io/drpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetHeldAmountRequest struct {
	Period               time.Time `protobuf:"bytes,1,opt,name=period,proto3,stdtime" json:"period"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHeldAmountRequest) Reset()         { *m = GetHeldAmountRequest{} }
func (m *GetHeldAmountRequest) String() string { return proto.CompactTextString(m) }
func (*GetHeldAmountRequest) ProtoMessage()    {}
func (*GetHeldAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{0}
}
func (m *GetHeldAmountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeldAmountRequest.Unmarshal(m, b)
}
func (m *GetHeldAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeldAmountRequest.Marshal(b, m, deterministic)
}
func (m *GetHeldAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeldAmountRequest.Merge(m, src)
}
func (m *GetHeldAmountRequest) XXX_Size() int {
	return xxx_messageInfo_GetHeldAmountRequest.Size(m)
}
func (m *GetHeldAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeldAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeldAmountRequest proto.InternalMessageInfo

func (m *GetHeldAmountRequest) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

type GetHeldAmountResponse struct {
	Period               time.Time `protobuf:"bytes,1,opt,name=period,proto3,stdtime" json:"period"`
	NodeId               NodeID    `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	CreatedAt            time.Time `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	Codes                string    `protobuf:"bytes,4,opt,name=codes,proto3" json:"codes,omitempty"`
	UsageAtRest          float32   `protobuf:"fixed32,5,opt,name=usage_at_rest,json=usageAtRest,proto3" json:"usage_at_rest,omitempty"`
	UsageGet             int64     `protobuf:"varint,6,opt,name=usage_get,json=usageGet,proto3" json:"usage_get,omitempty"`
	UsagePut             int64     `protobuf:"varint,7,opt,name=usage_put,json=usagePut,proto3" json:"usage_put,omitempty"`
	UsageGetRepair       int64     `protobuf:"varint,8,opt,name=usage_get_repair,json=usageGetRepair,proto3" json:"usage_get_repair,omitempty"`
	UsagePutRepair       int64     `protobuf:"varint,9,opt,name=usage_put_repair,json=usagePutRepair,proto3" json:"usage_put_repair,omitempty"`
	UsageGetAudit        int64     `protobuf:"varint,10,opt,name=usage_get_audit,json=usageGetAudit,proto3" json:"usage_get_audit,omitempty"`
	CompAtRest           int64     `protobuf:"varint,11,opt,name=comp_at_rest,json=compAtRest,proto3" json:"comp_at_rest,omitempty"`
	CompGet              int64     `protobuf:"varint,12,opt,name=comp_get,json=compGet,proto3" json:"comp_get,omitempty"`
	CompPut              int64     `protobuf:"varint,13,opt,name=comp_put,json=compPut,proto3" json:"comp_put,omitempty"`
	CompGetRepair        int64     `protobuf:"varint,14,opt,name=comp_get_repair,json=compGetRepair,proto3" json:"comp_get_repair,omitempty"`
	CompPutRepair        int64     `protobuf:"varint,15,opt,name=comp_put_repair,json=compPutRepair,proto3" json:"comp_put_repair,omitempty"`
	CompGetAudit         int64     `protobuf:"varint,16,opt,name=comp_get_audit,json=compGetAudit,proto3" json:"comp_get_audit,omitempty"`
	SurgePercent         int64     `protobuf:"varint,17,opt,name=surge_percent,json=surgePercent,proto3" json:"surge_percent,omitempty"`
	Held                 int64     `protobuf:"varint,18,opt,name=held,proto3" json:"held,omitempty"`
	Owed                 int64     `protobuf:"varint,19,opt,name=owed,proto3" json:"owed,omitempty"`
	Disposed             int64     `protobuf:"varint,20,opt,name=disposed,proto3" json:"disposed,omitempty"`
	Paid                 int64     `protobuf:"varint,21,opt,name=paid,proto3" json:"paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHeldAmountResponse) Reset()         { *m = GetHeldAmountResponse{} }
func (m *GetHeldAmountResponse) String() string { return proto.CompactTextString(m) }
func (*GetHeldAmountResponse) ProtoMessage()    {}
func (*GetHeldAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{1}
}
func (m *GetHeldAmountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeldAmountResponse.Unmarshal(m, b)
}
func (m *GetHeldAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeldAmountResponse.Marshal(b, m, deterministic)
}
func (m *GetHeldAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeldAmountResponse.Merge(m, src)
}
func (m *GetHeldAmountResponse) XXX_Size() int {
	return xxx_messageInfo_GetHeldAmountResponse.Size(m)
}
func (m *GetHeldAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeldAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeldAmountResponse proto.InternalMessageInfo

func (m *GetHeldAmountResponse) GetPeriod() time.Time {
	if m != nil {
		return m.Period
	}
	return time.Time{}
}

func (m *GetHeldAmountResponse) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *GetHeldAmountResponse) GetCodes() string {
	if m != nil {
		return m.Codes
	}
	return ""
}

func (m *GetHeldAmountResponse) GetUsageAtRest() float32 {
	if m != nil {
		return m.UsageAtRest
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGet() int64 {
	if m != nil {
		return m.UsageGet
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsagePut() int64 {
	if m != nil {
		return m.UsagePut
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGetRepair() int64 {
	if m != nil {
		return m.UsageGetRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsagePutRepair() int64 {
	if m != nil {
		return m.UsagePutRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetUsageGetAudit() int64 {
	if m != nil {
		return m.UsageGetAudit
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompAtRest() int64 {
	if m != nil {
		return m.CompAtRest
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGet() int64 {
	if m != nil {
		return m.CompGet
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompPut() int64 {
	if m != nil {
		return m.CompPut
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGetRepair() int64 {
	if m != nil {
		return m.CompGetRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompPutRepair() int64 {
	if m != nil {
		return m.CompPutRepair
	}
	return 0
}

func (m *GetHeldAmountResponse) GetCompGetAudit() int64 {
	if m != nil {
		return m.CompGetAudit
	}
	return 0
}

func (m *GetHeldAmountResponse) GetSurgePercent() int64 {
	if m != nil {
		return m.SurgePercent
	}
	return 0
}

func (m *GetHeldAmountResponse) GetHeld() int64 {
	if m != nil {
		return m.Held
	}
	return 0
}

func (m *GetHeldAmountResponse) GetOwed() int64 {
	if m != nil {
		return m.Owed
	}
	return 0
}

func (m *GetHeldAmountResponse) GetDisposed() int64 {
	if m != nil {
		return m.Disposed
	}
	return 0
}

func (m *GetHeldAmountResponse) GetPaid() int64 {
	if m != nil {
		return m.Paid
	}
	return 0
}

type GetAllPaystubsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPaystubsRequest) Reset()         { *m = GetAllPaystubsRequest{} }
func (m *GetAllPaystubsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPaystubsRequest) ProtoMessage()    {}
func (*GetAllPaystubsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{2}
}
func (m *GetAllPaystubsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaystubsRequest.Unmarshal(m, b)
}
func (m *GetAllPaystubsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaystubsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPaystubsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaystubsRequest.Merge(m, src)
}
func (m *GetAllPaystubsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPaystubsRequest.Size(m)
}
func (m *GetAllPaystubsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaystubsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaystubsRequest proto.InternalMessageInfo

type GetAllPaystubsResponse struct {
	Paystub              []*GetHeldAmountResponse `protobuf:"bytes,1,rep,name=paystub,proto3" json:"paystub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetAllPaystubsResponse) Reset()         { *m = GetAllPaystubsResponse{} }
func (m *GetAllPaystubsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPaystubsResponse) ProtoMessage()    {}
func (*GetAllPaystubsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c5d9f6e3ee97993, []int{3}
}
func (m *GetAllPaystubsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPaystubsResponse.Unmarshal(m, b)
}
func (m *GetAllPaystubsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPaystubsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPaystubsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPaystubsResponse.Merge(m, src)
}
func (m *GetAllPaystubsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPaystubsResponse.Size(m)
}
func (m *GetAllPaystubsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPaystubsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPaystubsResponse proto.InternalMessageInfo

func (m *GetAllPaystubsResponse) GetPaystub() []*GetHeldAmountResponse {
	if m != nil {
		return m.Paystub
	}
	return nil
}

func init() {
	proto.RegisterType((*GetHeldAmountRequest)(nil), "heldamount.GetHeldAmountRequest")
	proto.RegisterType((*GetHeldAmountResponse)(nil), "heldamount.GetHeldAmountResponse")
	proto.RegisterType((*GetAllPaystubsRequest)(nil), "heldamount.GetAllPaystubsRequest")
	proto.RegisterType((*GetAllPaystubsResponse)(nil), "heldamount.GetAllPaystubsResponse")
}

func init() { proto.RegisterFile("heldamount.proto", fileDescriptor_5c5d9f6e3ee97993) }

var fileDescriptor_5c5d9f6e3ee97993 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x86, 0x99, 0x5e, 0x72, 0x39, 0xb9, 0xb4, 0x98, 0x16, 0xcc, 0xb0, 0xc8, 0x30, 0xa0, 0x32,
	0xab, 0x54, 0x2a, 0x4b, 0xd8, 0xa4, 0x20, 0x95, 0x6e, 0x50, 0x18, 0x8a, 0x90, 0xd8, 0x44, 0x93,
	0xf8, 0x30, 0x8c, 0x94, 0xc4, 0x66, 0x6c, 0x0b, 0xf5, 0x2d, 0x78, 0x1c, 0x1e, 0x81, 0x67, 0x60,
	0x51, 0xde, 0x04, 0x21, 0xdb, 0xe3, 0x4c, 0x08, 0xa8, 0x08, 0xb1, 0xb3, 0xff, 0xf3, 0x9d, 0xdf,
	0xe7, 0x4f, 0xe6, 0xc0, 0xfe, 0x07, 0x9c, 0xb3, 0x6c, 0xc1, 0xf5, 0x52, 0x0d, 0x45, 0xc9, 0x15,
	0x27, 0x50, 0x2b, 0x21, 0xe4, 0x3c, 0xe7, 0x4e, 0x0f, 0x07, 0x39, 0xe7, 0xf9, 0x1c, 0x8f, 0xed,
	0x6d, 0xaa, 0xdf, 0x1f, 0xab, 0x62, 0x81, 0x52, 0x65, 0x0b, 0xe1, 0x80, 0xf8, 0x02, 0x0e, 0xce,
	0x50, 0xbd, 0xc0, 0x39, 0x1b, 0xd9, 0xee, 0x14, 0x3f, 0x6a, 0x94, 0x8a, 0x3c, 0x85, 0x86, 0xc0,
	0xb2, 0xe0, 0x8c, 0x06, 0x51, 0x90, 0x74, 0x4e, 0xc2, 0xa1, 0x73, 0x1a, 0x7a, 0xa7, 0xe1, 0x85,
	0x77, 0x3a, 0x6d, 0x7d, 0xbd, 0x1a, 0xdc, 0xf8, 0xfc, 0x7d, 0x10, 0xa4, 0x55, 0x4f, 0xfc, 0x63,
	0x17, 0x0e, 0x37, 0x6c, 0xa5, 0xe0, 0x4b, 0x89, 0xff, 0xe7, 0x4b, 0x1e, 0x41, 0x73, 0xc9, 0x19,
	0x4e, 0x0a, 0x46, 0xb7, 0xa2, 0x20, 0xe9, 0x9e, 0xf6, 0x0d, 0xf2, 0xed, 0x6a, 0xd0, 0x78, 0xc9,
	0x19, 0x9e, 0x3f, 0x4f, 0x1b, 0xa6, 0x7c, 0xce, 0xc8, 0x33, 0x80, 0x59, 0x89, 0x99, 0x42, 0x36,
	0xc9, 0x14, 0xdd, 0xfe, 0x87, 0xa7, 0xda, 0x55, 0xdf, 0x48, 0x91, 0x03, 0xd8, 0x9d, 0x71, 0x86,
	0x92, 0xee, 0x44, 0x41, 0xd2, 0x4e, 0xdd, 0x85, 0xc4, 0xd0, 0xd3, 0x32, 0xcb, 0x71, 0x92, 0xa9,
	0x49, 0x89, 0x52, 0xd1, 0xdd, 0x28, 0x48, 0xb6, 0xd2, 0x8e, 0x15, 0x47, 0x26, 0xa9, 0x22, 0xf7,
	0xa0, 0xed, 0x98, 0x1c, 0x15, 0x6d, 0x44, 0x41, 0xb2, 0x9d, 0xb6, 0xac, 0x70, 0x86, 0x6b, 0x45,
	0xa1, 0x15, 0x6d, 0xae, 0x15, 0xc7, 0x5a, 0x91, 0x04, 0xf6, 0x57, 0x9d, 0x93, 0x12, 0x45, 0x56,
	0x94, 0xb4, 0x65, 0x99, 0xbe, 0x37, 0x48, 0xad, 0x5a, 0x93, 0x42, 0xaf, 0xc8, 0xf6, 0x1a, 0x39,
	0xd6, 0x9e, 0x3c, 0x82, 0xbd, 0xda, 0x33, 0xd3, 0xac, 0x50, 0x14, 0x2c, 0xd8, 0xf3, 0x96, 0x23,
	0x23, 0x92, 0x08, 0xba, 0x33, 0xbe, 0x10, 0xab, 0x60, 0x1d, 0x0b, 0x81, 0xd1, 0xaa, 0x5c, 0x77,
	0xa1, 0x65, 0x09, 0x13, 0xab, 0x6b, 0xab, 0x4d, 0x73, 0x37, 0xa9, 0x7c, 0xc9, 0x84, 0xea, 0xd5,
	0x25, 0x93, 0xe9, 0x08, 0xf6, 0x7c, 0x97, 0x1f, 0xb4, 0xef, 0xde, 0xaf, 0x9a, 0xeb, 0x39, 0xbd,
	0x85, 0xe7, 0xf6, 0x6a, 0xae, 0xce, 0xf3, 0x10, 0xfa, 0x2b, 0x3f, 0x17, 0x67, 0xdf, 0x62, 0xdd,
	0xca, 0xce, 0xa5, 0x79, 0x00, 0x3d, 0xa9, 0x4b, 0xf3, 0xfb, 0x60, 0x39, 0xc3, 0xa5, 0xa2, 0x37,
	0x1d, 0x64, 0xc5, 0xb1, 0xd3, 0x08, 0x81, 0x1d, 0xb3, 0x39, 0x94, 0xd8, 0x9a, 0x3d, 0x1b, 0x8d,
	0x7f, 0x42, 0x46, 0x6f, 0x39, 0xcd, 0x9c, 0x49, 0x08, 0x2d, 0x56, 0x48, 0xc1, 0x25, 0x32, 0x7a,
	0xe0, 0xfe, 0x32, 0x7f, 0x37, 0xbc, 0xc8, 0x0a, 0x46, 0x0f, 0x1d, 0x6f, 0xce, 0xf1, 0x1d, 0xfb,
	0xfd, 0x8f, 0xe6, 0xf3, 0x71, 0x76, 0x29, 0x95, 0x9e, 0xca, 0x6a, 0xaf, 0xe2, 0x37, 0x70, 0x7b,
	0xb3, 0x50, 0x6d, 0xc6, 0x13, 0x68, 0x0a, 0xa7, 0xd1, 0x20, 0xda, 0x4e, 0x3a, 0x27, 0xf7, 0x87,
	0x6b, 0x6b, 0xfe, 0xc7, 0x6d, 0x4a, 0x7d, 0xc7, 0xc9, 0x97, 0x00, 0xa0, 0xae, 0x93, 0x57, 0x00,
	0x67, 0xa8, 0xc6, 0xd9, 0xe5, 0x6b, 0xa5, 0xa7, 0x24, 0xba, 0xc6, 0xc8, 0x4e, 0x15, 0xfe, 0xfd,
	0x29, 0xf2, 0x16, 0xfa, 0xbf, 0x0e, 0x4e, 0x36, 0x9b, 0x7e, 0x4f, 0x1b, 0xc6, 0xd7, 0x21, 0xce,
	0xf8, 0x74, 0xe7, 0xdd, 0x96, 0x98, 0x4e, 0x1b, 0x76, 0x29, 0x1f, 0xff, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0x99, 0x22, 0x53, 0xdb, 0x04, 0x00, 0x00,
}

// --- DRPC BEGIN ---

type DRPCHeldAmountClient interface {
	DRPCConn() drpc.Conn

	GetPayStub(ctx context.Context, in *GetHeldAmountRequest) (*GetHeldAmountResponse, error)
	GetAllPaystubs(ctx context.Context, in *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error)
}

type drpcHeldAmountClient struct {
	cc drpc.Conn
}

func NewDRPCHeldAmountClient(cc drpc.Conn) DRPCHeldAmountClient {
	return &drpcHeldAmountClient{cc}
}

func (c *drpcHeldAmountClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcHeldAmountClient) GetPayStub(ctx context.Context, in *GetHeldAmountRequest) (*GetHeldAmountResponse, error) {
	out := new(GetHeldAmountResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetPayStub", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcHeldAmountClient) GetAllPaystubs(ctx context.Context, in *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error) {
	out := new(GetAllPaystubsResponse)
	err := c.cc.Invoke(ctx, "/heldamount.HeldAmount/GetAllPaystubs", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCHeldAmountServer interface {
	GetPayStub(context.Context, *GetHeldAmountRequest) (*GetHeldAmountResponse, error)
	GetAllPaystubs(context.Context, *GetAllPaystubsRequest) (*GetAllPaystubsResponse, error)
}

type DRPCHeldAmountDescription struct{}

func (DRPCHeldAmountDescription) NumMethods() int { return 2 }

func (DRPCHeldAmountDescription) Method(n int) (string, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/heldamount.HeldAmount/GetPayStub",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetPayStub(
						ctx,
						in1.(*GetHeldAmountRequest),
					)
			}, DRPCHeldAmountServer.GetPayStub, true
	case 1:
		return "/heldamount.HeldAmount/GetAllPaystubs",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCHeldAmountServer).
					GetAllPaystubs(
						ctx,
						in1.(*GetAllPaystubsRequest),
					)
			}, DRPCHeldAmountServer.GetAllPaystubs, true
	default:
		return "", nil, nil, false
	}
}

func DRPCRegisterHeldAmount(mux drpc.Mux, impl DRPCHeldAmountServer) error {
	return mux.Register(impl, DRPCHeldAmountDescription{})
}

type DRPCHeldAmount_GetPayStubStream interface {
	drpc.Stream
	SendAndClose(*GetHeldAmountResponse) error
}

type drpcHeldAmountGetPayStubStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetPayStubStream) SendAndClose(m *GetHeldAmountResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCHeldAmount_GetAllPaystubsStream interface {
	drpc.Stream
	SendAndClose(*GetAllPaystubsResponse) error
}

type drpcHeldAmountGetAllPaystubsStream struct {
	drpc.Stream
}

func (x *drpcHeldAmountGetAllPaystubsStream) SendAndClose(m *GetAllPaystubsResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

// --- DRPC END ---
