// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nodestats.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"

	drpc "storj.io/drpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ReputationStats struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount         int64    `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ReputationAlpha      float64  `protobuf:"fixed64,3,opt,name=reputation_alpha,json=reputationAlpha,proto3" json:"reputation_alpha,omitempty"`
	ReputationBeta       float64  `protobuf:"fixed64,4,opt,name=reputation_beta,json=reputationBeta,proto3" json:"reputation_beta,omitempty"`
	ReputationScore      float64  `protobuf:"fixed64,5,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReputationStats) Reset()         { *m = ReputationStats{} }
func (m *ReputationStats) String() string { return proto.CompactTextString(m) }
func (*ReputationStats) ProtoMessage()    {}
func (*ReputationStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{0}
}
func (m *ReputationStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReputationStats.Unmarshal(m, b)
}
func (m *ReputationStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReputationStats.Marshal(b, m, deterministic)
}
func (m *ReputationStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReputationStats.Merge(m, src)
}
func (m *ReputationStats) XXX_Size() int {
	return xxx_messageInfo_ReputationStats.Size(m)
}
func (m *ReputationStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ReputationStats.DiscardUnknown(m)
}

var xxx_messageInfo_ReputationStats proto.InternalMessageInfo

func (m *ReputationStats) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ReputationStats) GetSuccessCount() int64 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

func (m *ReputationStats) GetReputationAlpha() float64 {
	if m != nil {
		return m.ReputationAlpha
	}
	return 0
}

func (m *ReputationStats) GetReputationBeta() float64 {
	if m != nil {
		return m.ReputationBeta
	}
	return 0
}

func (m *ReputationStats) GetReputationScore() float64 {
	if m != nil {
		return m.ReputationScore
	}
	return 0
}

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{1}
}
func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

type GetStatsResponse struct {
	UptimeCheck          *ReputationStats `protobuf:"bytes,1,opt,name=uptime_check,json=uptimeCheck,proto3" json:"uptime_check,omitempty"`
	AuditCheck           *ReputationStats `protobuf:"bytes,2,opt,name=audit_check,json=auditCheck,proto3" json:"audit_check,omitempty"`
	Disqualified         *time.Time       `protobuf:"bytes,3,opt,name=disqualified,proto3,stdtime" json:"disqualified,omitempty"`
	Suspended            *time.Time       `protobuf:"bytes,4,opt,name=suspended,proto3,stdtime" json:"suspended,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetStatsResponse) Reset()         { *m = GetStatsResponse{} }
func (m *GetStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatsResponse) ProtoMessage()    {}
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{2}
}
func (m *GetStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsResponse.Unmarshal(m, b)
}
func (m *GetStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsResponse.Merge(m, src)
}
func (m *GetStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatsResponse.Size(m)
}
func (m *GetStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsResponse proto.InternalMessageInfo

func (m *GetStatsResponse) GetUptimeCheck() *ReputationStats {
	if m != nil {
		return m.UptimeCheck
	}
	return nil
}

func (m *GetStatsResponse) GetAuditCheck() *ReputationStats {
	if m != nil {
		return m.AuditCheck
	}
	return nil
}

func (m *GetStatsResponse) GetDisqualified() *time.Time {
	if m != nil {
		return m.Disqualified
	}
	return nil
}

func (m *GetStatsResponse) GetSuspended() *time.Time {
	if m != nil {
		return m.Suspended
	}
	return nil
}

type DailyStorageUsageRequest struct {
	From                 time.Time `protobuf:"bytes,1,opt,name=from,proto3,stdtime" json:"from"`
	To                   time.Time `protobuf:"bytes,2,opt,name=to,proto3,stdtime" json:"to"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DailyStorageUsageRequest) Reset()         { *m = DailyStorageUsageRequest{} }
func (m *DailyStorageUsageRequest) String() string { return proto.CompactTextString(m) }
func (*DailyStorageUsageRequest) ProtoMessage()    {}
func (*DailyStorageUsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{3}
}
func (m *DailyStorageUsageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyStorageUsageRequest.Unmarshal(m, b)
}
func (m *DailyStorageUsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyStorageUsageRequest.Marshal(b, m, deterministic)
}
func (m *DailyStorageUsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyStorageUsageRequest.Merge(m, src)
}
func (m *DailyStorageUsageRequest) XXX_Size() int {
	return xxx_messageInfo_DailyStorageUsageRequest.Size(m)
}
func (m *DailyStorageUsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyStorageUsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DailyStorageUsageRequest proto.InternalMessageInfo

func (m *DailyStorageUsageRequest) GetFrom() time.Time {
	if m != nil {
		return m.From
	}
	return time.Time{}
}

func (m *DailyStorageUsageRequest) GetTo() time.Time {
	if m != nil {
		return m.To
	}
	return time.Time{}
}

type DailyStorageUsageResponse struct {
	NodeId               NodeID                                    `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	DailyStorageUsage    []*DailyStorageUsageResponse_StorageUsage `protobuf:"bytes,2,rep,name=daily_storage_usage,json=dailyStorageUsage,proto3" json:"daily_storage_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *DailyStorageUsageResponse) Reset()         { *m = DailyStorageUsageResponse{} }
func (m *DailyStorageUsageResponse) String() string { return proto.CompactTextString(m) }
func (*DailyStorageUsageResponse) ProtoMessage()    {}
func (*DailyStorageUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{4}
}
func (m *DailyStorageUsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyStorageUsageResponse.Unmarshal(m, b)
}
func (m *DailyStorageUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyStorageUsageResponse.Marshal(b, m, deterministic)
}
func (m *DailyStorageUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyStorageUsageResponse.Merge(m, src)
}
func (m *DailyStorageUsageResponse) XXX_Size() int {
	return xxx_messageInfo_DailyStorageUsageResponse.Size(m)
}
func (m *DailyStorageUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyStorageUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DailyStorageUsageResponse proto.InternalMessageInfo

func (m *DailyStorageUsageResponse) GetDailyStorageUsage() []*DailyStorageUsageResponse_StorageUsage {
	if m != nil {
		return m.DailyStorageUsage
	}
	return nil
}

type DailyStorageUsageResponse_StorageUsage struct {
	AtRestTotal          float64   `protobuf:"fixed64,1,opt,name=at_rest_total,json=atRestTotal,proto3" json:"at_rest_total,omitempty"`
	Timestamp            time.Time `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DailyStorageUsageResponse_StorageUsage) Reset() {
	*m = DailyStorageUsageResponse_StorageUsage{}
}
func (m *DailyStorageUsageResponse_StorageUsage) String() string { return proto.CompactTextString(m) }
func (*DailyStorageUsageResponse_StorageUsage) ProtoMessage()    {}
func (*DailyStorageUsageResponse_StorageUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{4, 0}
}
func (m *DailyStorageUsageResponse_StorageUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyStorageUsageResponse_StorageUsage.Unmarshal(m, b)
}
func (m *DailyStorageUsageResponse_StorageUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyStorageUsageResponse_StorageUsage.Marshal(b, m, deterministic)
}
func (m *DailyStorageUsageResponse_StorageUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyStorageUsageResponse_StorageUsage.Merge(m, src)
}
func (m *DailyStorageUsageResponse_StorageUsage) XXX_Size() int {
	return xxx_messageInfo_DailyStorageUsageResponse_StorageUsage.Size(m)
}
func (m *DailyStorageUsageResponse_StorageUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyStorageUsageResponse_StorageUsage.DiscardUnknown(m)
}

var xxx_messageInfo_DailyStorageUsageResponse_StorageUsage proto.InternalMessageInfo

func (m *DailyStorageUsageResponse_StorageUsage) GetAtRestTotal() float64 {
	if m != nil {
		return m.AtRestTotal
	}
	return 0
}

func (m *DailyStorageUsageResponse_StorageUsage) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

type PricingModelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingModelRequest) Reset()         { *m = PricingModelRequest{} }
func (m *PricingModelRequest) String() string { return proto.CompactTextString(m) }
func (*PricingModelRequest) ProtoMessage()    {}
func (*PricingModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{5}
}
func (m *PricingModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingModelRequest.Unmarshal(m, b)
}
func (m *PricingModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingModelRequest.Marshal(b, m, deterministic)
}
func (m *PricingModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingModelRequest.Merge(m, src)
}
func (m *PricingModelRequest) XXX_Size() int {
	return xxx_messageInfo_PricingModelRequest.Size(m)
}
func (m *PricingModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PricingModelRequest proto.InternalMessageInfo

type PricingModelResponse struct {
	EgressBandwidthPrice int64    `protobuf:"varint,1,opt,name=egress_bandwidth_price,json=egressBandwidthPrice,proto3" json:"egress_bandwidth_price,omitempty"`
	RepairBandwidthPrice int64    `protobuf:"varint,2,opt,name=repair_bandwidth_price,json=repairBandwidthPrice,proto3" json:"repair_bandwidth_price,omitempty"`
	DiskSpacePrice       int64    `protobuf:"varint,3,opt,name=disk_space_price,json=diskSpacePrice,proto3" json:"disk_space_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingModelResponse) Reset()         { *m = PricingModelResponse{} }
func (m *PricingModelResponse) String() string { return proto.CompactTextString(m) }
func (*PricingModelResponse) ProtoMessage()    {}
func (*PricingModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0b184ee117142aa, []int{6}
}
func (m *PricingModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingModelResponse.Unmarshal(m, b)
}
func (m *PricingModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingModelResponse.Marshal(b, m, deterministic)
}
func (m *PricingModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingModelResponse.Merge(m, src)
}
func (m *PricingModelResponse) XXX_Size() int {
	return xxx_messageInfo_PricingModelResponse.Size(m)
}
func (m *PricingModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PricingModelResponse proto.InternalMessageInfo

func (m *PricingModelResponse) GetEgressBandwidthPrice() int64 {
	if m != nil {
		return m.EgressBandwidthPrice
	}
	return 0
}

func (m *PricingModelResponse) GetRepairBandwidthPrice() int64 {
	if m != nil {
		return m.RepairBandwidthPrice
	}
	return 0
}

func (m *PricingModelResponse) GetDiskSpacePrice() int64 {
	if m != nil {
		return m.DiskSpacePrice
	}
	return 0
}

func init() {
	proto.RegisterType((*ReputationStats)(nil), "nodestats.ReputationStats")
	proto.RegisterType((*GetStatsRequest)(nil), "nodestats.GetStatsRequest")
	proto.RegisterType((*GetStatsResponse)(nil), "nodestats.GetStatsResponse")
	proto.RegisterType((*DailyStorageUsageRequest)(nil), "nodestats.DailyStorageUsageRequest")
	proto.RegisterType((*DailyStorageUsageResponse)(nil), "nodestats.DailyStorageUsageResponse")
	proto.RegisterType((*DailyStorageUsageResponse_StorageUsage)(nil), "nodestats.DailyStorageUsageResponse.StorageUsage")
	proto.RegisterType((*PricingModelRequest)(nil), "nodestats.PricingModelRequest")
	proto.RegisterType((*PricingModelResponse)(nil), "nodestats.PricingModelResponse")
}

func init() { proto.RegisterFile("nodestats.proto", fileDescriptor_e0b184ee117142aa) }

var fileDescriptor_e0b184ee117142aa = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xec, 0xf4, 0x2b, 0xed, 0x4d, 0xda, 0xb4, 0xd3, 0x82, 0x42, 0x90, 0x48, 0xe5, 0x22,
	0x35, 0x6c, 0x52, 0x51, 0xba, 0x40, 0x42, 0x2c, 0x48, 0x2b, 0x41, 0x17, 0xfc, 0xc8, 0x29, 0x1b,
	0x16, 0x58, 0x13, 0xcf, 0xad, 0x3b, 0xaa, 0xeb, 0x71, 0x3d, 0x63, 0x10, 0x4b, 0xb6, 0xac, 0x78,
	0x00, 0x24, 0x5e, 0x80, 0x07, 0xe1, 0x09, 0x58, 0xb0, 0x28, 0xaf, 0x82, 0x66, 0xc6, 0x89, 0x5d,
	0xf7, 0x87, 0xb2, 0xf4, 0xb9, 0xe7, 0x9c, 0xcc, 0x9c, 0x33, 0x37, 0xd0, 0x4e, 0x04, 0x43, 0xa9,
	0xa8, 0x92, 0x83, 0x34, 0x13, 0x4a, 0x90, 0xf9, 0x29, 0xd0, 0x85, 0x48, 0x44, 0xc2, 0xc2, 0xdd,
	0x5e, 0x24, 0x44, 0x14, 0xe3, 0xa6, 0xf9, 0x1a, 0xe7, 0x07, 0x9b, 0x8a, 0x1f, 0x6b, 0xda, 0x71,
	0x6a, 0x09, 0xde, 0x4f, 0x07, 0xda, 0x3e, 0xa6, 0xb9, 0xa2, 0x8a, 0x8b, 0x64, 0xa4, 0x0d, 0x48,
	0x0f, 0x9a, 0x4a, 0x28, 0x1a, 0x07, 0xa1, 0xc8, 0x13, 0xd5, 0x71, 0xd6, 0x9c, 0x7e, 0xc3, 0x07,
	0x03, 0xed, 0x68, 0x84, 0xac, 0xc3, 0x82, 0xcc, 0xc3, 0x10, 0xa5, 0x2c, 0x28, 0xae, 0xa1, 0xb4,
	0x0a, 0xd0, 0x92, 0xee, 0xc3, 0x52, 0x36, 0x35, 0x0e, 0x68, 0x9c, 0x1e, 0xd2, 0x4e, 0x63, 0xcd,
	0xe9, 0x3b, 0x7e, 0xbb, 0xc4, 0x9f, 0x6a, 0x98, 0x6c, 0x40, 0x05, 0x0a, 0xc6, 0xa8, 0x68, 0x67,
	0xc6, 0x30, 0x17, 0x4b, 0x78, 0x88, 0x8a, 0xd6, 0x3c, 0x65, 0x28, 0x32, 0xec, 0xfc, 0x5f, 0xf7,
	0x1c, 0x69, 0xd8, 0x5b, 0x86, 0xf6, 0x33, 0x54, 0xe6, 0x42, 0x3e, 0x9e, 0xe4, 0x28, 0x95, 0xf7,
	0xd5, 0x85, 0xa5, 0x12, 0x93, 0xa9, 0x48, 0x24, 0x92, 0x27, 0xd0, 0xca, 0x53, 0x9d, 0x4a, 0x10,
	0x1e, 0x62, 0x78, 0x64, 0x6e, 0xdb, 0xdc, 0xea, 0x0e, 0xca, 0x80, 0x6b, 0xf1, 0xf8, 0x4d, 0xcb,
	0xdf, 0xd1, 0x74, 0xf2, 0x18, 0x9a, 0x34, 0x67, 0x5c, 0x15, 0x6a, 0xf7, 0xaf, 0x6a, 0x30, 0x74,
	0x2b, 0x7e, 0x0e, 0x2d, 0xc6, 0xe5, 0x49, 0x4e, 0x63, 0x7e, 0xc0, 0x91, 0x99, 0x78, 0xb4, 0xda,
	0x96, 0x36, 0x98, 0x94, 0x36, 0xd8, 0x9f, 0x94, 0x36, 0x9c, 0xfb, 0x71, 0xda, 0x73, 0xbe, 0xfc,
	0xee, 0x39, 0xfe, 0x19, 0x25, 0x19, 0xc2, 0xbc, 0xcc, 0x65, 0x8a, 0x09, 0x43, 0x66, 0xb2, 0xbb,
	0xae, 0x4d, 0x29, 0xf3, 0x3e, 0x3b, 0xd0, 0xd9, 0xa5, 0x3c, 0xfe, 0x38, 0x52, 0x22, 0xa3, 0x11,
	0xbe, 0x91, 0x34, 0xc2, 0x22, 0x3b, 0xf2, 0x08, 0x66, 0x0e, 0x32, 0x71, 0x3c, 0x8d, 0xe7, 0x6a,
	0xef, 0xff, 0x8c, 0xb7, 0x51, 0x90, 0x6d, 0x70, 0x95, 0x98, 0x06, 0x73, 0x1d, 0x9d, 0xab, 0x84,
	0xf7, 0xcd, 0x85, 0xdb, 0x17, 0x1c, 0xa6, 0x28, 0x6d, 0x03, 0x6e, 0xe8, 0x84, 0x03, 0xce, 0xcc,
	0x81, 0x5a, 0xc3, 0x45, 0x2d, 0xfe, 0x75, 0xda, 0x9b, 0x7d, 0x29, 0x18, 0xee, 0xed, 0xfa, 0xb3,
	0x7a, 0xbc, 0xc7, 0x08, 0x85, 0x15, 0xa6, 0x5d, 0x02, 0x69, 0x6d, 0x82, 0x5c, 0xfb, 0x74, 0xdc,
	0xb5, 0x46, 0xbf, 0xb9, 0xf5, 0xa0, 0x52, 0xd3, 0xa5, 0xbf, 0x35, 0x38, 0x03, 0x2e, 0xb3, 0x3a,
	0xaf, 0xfb, 0x1e, 0x5a, 0xd5, 0x6f, 0xe2, 0xc1, 0x02, 0x55, 0x41, 0x86, 0x52, 0x05, 0x66, 0x65,
	0xcc, 0x09, 0x1d, 0xbf, 0x49, 0x95, 0x8f, 0x52, 0xed, 0x6b, 0x48, 0xd7, 0x35, 0x5d, 0xc4, 0x7f,
	0x8a, 0xa6, 0x94, 0x79, 0x37, 0x61, 0xe5, 0x75, 0xc6, 0x43, 0x9e, 0x44, 0x2f, 0x04, 0xc3, 0x78,
	0xf2, 0xc8, 0xbf, 0x3b, 0xb0, 0x7a, 0x16, 0x2f, 0x32, 0xdb, 0x86, 0x5b, 0x18, 0x65, 0x7a, 0x67,
	0xc7, 0x34, 0x61, 0x1f, 0x38, 0x53, 0x87, 0x41, 0x9a, 0xf1, 0x10, 0x8b, 0x05, 0x5f, 0xb5, 0xd3,
	0xe1, 0x64, 0xa8, 0x4d, 0x8c, 0x2a, 0xc3, 0x94, 0xf2, 0xec, 0x9c, 0xca, 0xee, 0xfc, 0xaa, 0x9d,
	0xd6, 0x54, 0x7d, 0x58, 0x62, 0x5c, 0x1e, 0x05, 0x32, 0xa5, 0x21, 0x16, 0xfc, 0x86, 0xe1, 0x2f,
	0x6a, 0x7c, 0xa4, 0x61, 0xc3, 0xdc, 0xfa, 0xe4, 0xc2, 0xbc, 0xee, 0xcc, 0xfe, 0xf3, 0xec, 0xc0,
	0xdc, 0x64, 0x41, 0x49, 0x75, 0x89, 0x6a, 0x9b, 0xdc, 0xbd, 0x73, 0xe1, 0xac, 0xb8, 0xe8, 0x3b,
	0x58, 0x3e, 0xd7, 0x26, 0x59, 0xbf, 0xba, 0x6b, 0x6b, 0x7b, 0xef, 0x3a, 0x0f, 0x82, 0xbc, 0x82,
	0x56, 0x35, 0x60, 0x72, 0xb7, 0xa2, 0xba, 0xa0, 0x91, 0x6e, 0xef, 0xd2, 0xb9, 0x35, 0x1c, 0xce,
	0xbc, 0x75, 0xd3, 0xf1, 0x78, 0xd6, 0x14, 0xff, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x62, 0xd9, 0x8a, 0xdb, 0x05, 0x00, 0x00,
}

// --- DRPC BEGIN ---

type DRPCNodeStatsClient interface {
	DRPCConn() drpc.Conn

	GetStats(ctx context.Context, in *GetStatsRequest) (*GetStatsResponse, error)
	DailyStorageUsage(ctx context.Context, in *DailyStorageUsageRequest) (*DailyStorageUsageResponse, error)
	PricingModel(ctx context.Context, in *PricingModelRequest) (*PricingModelResponse, error)
}

type drpcNodeStatsClient struct {
	cc drpc.Conn
}

func NewDRPCNodeStatsClient(cc drpc.Conn) DRPCNodeStatsClient {
	return &drpcNodeStatsClient{cc}
}

func (c *drpcNodeStatsClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcNodeStatsClient) GetStats(ctx context.Context, in *GetStatsRequest) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/nodestats.NodeStats/GetStats", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcNodeStatsClient) DailyStorageUsage(ctx context.Context, in *DailyStorageUsageRequest) (*DailyStorageUsageResponse, error) {
	out := new(DailyStorageUsageResponse)
	err := c.cc.Invoke(ctx, "/nodestats.NodeStats/DailyStorageUsage", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcNodeStatsClient) PricingModel(ctx context.Context, in *PricingModelRequest) (*PricingModelResponse, error) {
	out := new(PricingModelResponse)
	err := c.cc.Invoke(ctx, "/nodestats.NodeStats/PricingModel", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCNodeStatsServer interface {
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	DailyStorageUsage(context.Context, *DailyStorageUsageRequest) (*DailyStorageUsageResponse, error)
	PricingModel(context.Context, *PricingModelRequest) (*PricingModelResponse, error)
}

type DRPCNodeStatsDescription struct{}

func (DRPCNodeStatsDescription) NumMethods() int { return 3 }

func (DRPCNodeStatsDescription) Method(n int) (string, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/nodestats.NodeStats/GetStats",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCNodeStatsServer).
					GetStats(
						ctx,
						in1.(*GetStatsRequest),
					)
			}, DRPCNodeStatsServer.GetStats, true
	case 1:
		return "/nodestats.NodeStats/DailyStorageUsage",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCNodeStatsServer).
					DailyStorageUsage(
						ctx,
						in1.(*DailyStorageUsageRequest),
					)
			}, DRPCNodeStatsServer.DailyStorageUsage, true
	case 2:
		return "/nodestats.NodeStats/PricingModel",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCNodeStatsServer).
					PricingModel(
						ctx,
						in1.(*PricingModelRequest),
					)
			}, DRPCNodeStatsServer.PricingModel, true
	default:
		return "", nil, nil, false
	}
}

func DRPCRegisterNodeStats(mux drpc.Mux, impl DRPCNodeStatsServer) error {
	return mux.Register(impl, DRPCNodeStatsDescription{})
}

type DRPCNodeStats_GetStatsStream interface {
	drpc.Stream
	SendAndClose(*GetStatsResponse) error
}

type drpcNodeStatsGetStatsStream struct {
	drpc.Stream
}

func (x *drpcNodeStatsGetStatsStream) SendAndClose(m *GetStatsResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCNodeStats_DailyStorageUsageStream interface {
	drpc.Stream
	SendAndClose(*DailyStorageUsageResponse) error
}

type drpcNodeStatsDailyStorageUsageStream struct {
	drpc.Stream
}

func (x *drpcNodeStatsDailyStorageUsageStream) SendAndClose(m *DailyStorageUsageResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCNodeStats_PricingModelStream interface {
	drpc.Stream
	SendAndClose(*PricingModelResponse) error
}

type drpcNodeStatsPricingModelStream struct {
	drpc.Stream
}

func (x *drpcNodeStatsPricingModelStream) SendAndClose(m *PricingModelResponse) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

// --- DRPC END ---
